### ISSUE TITLE
[LICENSE] Some clearification on the license and state of the repository.

### ISSUE THREAD

**Issue by Malte0621** [AqwamCreates/DataPredict#2]
Its a bit confusing that you don't have a `LICENSE` or `LICENSE.md` file in your project and that it specifically states "THIS IS A PROPRIETARY SOURCE CODE! NOT OPEN SOURCE!" which means that the source code is a private and NOT for public use at all.

Open-Source does **NOT** mean that its free to use for anything, there are many different standard and custom licenses used by Open-Source software, you may see some examples of popular standard licenses here: https://choosealicense.com/licenses/

So, either this project is open-source but with a license that prohibits commercial use, modification, redistribution, etc.. OR its proprietary source code that should NOT be public and was made public by accident, in that case you may need to make it private asap and DMCA take down re-uploads via GitHub (possibly involving a lawyer and lawsuits).

Also, in the `README.md` it states:
```
GIVE CREDIT AND SOURCE WHEN USING THIS LIBRARY IF YOUR USAGE FALLS UNDER ONE OF THESE CATEGORIES:

    USED AS A VIDEO OR ARTICLE CONTENT
    USED AS RESEARCH AND EDUCATION CONTENT
```
Does this mean no credit is required for usage in video games or platforms like Roblox?

Just want to make sure that the provided information on this repository is valid and makes sense.

**Comment by AqwamCreates** [comment]
This is what they consider as "Source-Available" code. Although the open-source and source-available may be seem the same, source available heavily leans towards proprietary code.

Such license exist in Unreal Engine and many others in this list: https://en.wikipedia.org/wiki/List_of_proprietary_source-available_software

That being said, I just placed that license so that it deters companies who deals with brand names (like Amazon), as well as companies that have games that generates large revenue / player base. If you don't fall under this, we can arrange a license agreement that allows you use it for free (with commercial use), provided that you give attribution.

Anyways for credit part, it is required, but if you are a small company / solo developer, you can put it somewhere hidden. It just that I want to make sure the big players give me exposure if they do somehow use it for non-commercial use.

Also, the DataPredict license is written without a lawyer. I plan to change the license so that it satisfy the above, but I don't really have the money to do so. So I made sure the commercial use is extremely restrictive because I do not want to make mistakes that could cost me in the future. For others, 99% I won't care.

**Comment by Malte0621** [comment]
Alright, thanks for clarifying, I'm just getting into AI and Neural Network and I've tried brain.js & brain/rl, which I thought was really cool and easy to use. I can't wait to make cool things on Roblox using your library too 😄 

Anyways, again, thank you for clarifying.
